# Generated by Django 5.0.6 on 2024-08-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
